version: 2.0

machine:
  services:
    - docker

dependencies:
    override:
       - sudo pip install --upgrade pip
       - sudo pip install docker-compose
       - docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD

jobs:

  "machine-learning":
    working_directory: ~/tmp
    machine: true
    steps:
      - checkout
      - run:
          name: Building machine learning image
          command: |
                      echo $PWD
                      ls -aslh .
                      ls -aslh ~
                      ls -aslh ~/tmp
             docker-compose -f machine_learning/docker-compose.yml up -d && docker stop $(docker ps -a -q)
      - persist_to_workspace:
                root: .
                paths:
                  - .

  "machine-learning-publish":
    machine: true
    steps:
      - run:
          name: Publishing machine learning image
          command:
             - docker tag machinelearning_jupyter $DOCKER_HUB_USER_ID/machine-learning-jupyter:0.0.1
             - docker tag machinelearning_jupyter $DOCKER_HUB_USER_ID/machine-learning-jupyter:latest
             - docker push $DOCKER_HUB_USER_ID/machine-learning-jupyter:0.0.1
             - docker push $DOCKER_HUB_USER_ID/machine-learning-jupyter:latest

  "latex":
    machine: true
    steps:
      - run:
          name: Building latex image
          command: docker-compose -f latex/docker-compose.yml  up -d && docker stop $(docker ps -a -q)

  "latex-publish":
    machine: true
    steps:
      - run:
          name: Publishing latex image
          command:
                - docker tag latex_jupyter $DOCKER_HUB_USER_ID/latex-jupyter:0.0.1
                - docker tag latex_jupyter $DOCKER_HUB_USER_ID/latex-jupyter:latest
                - docker push $DOCKER_HUB_USER_ID/latex-jupyter:0.0.1
                - docker push $DOCKER_HUB_USER_ID/latex-jupyter:latest

  "graphviz":
    machine: true
    steps:
      - run:
          name: Building graphviz image
          command: docker-compose -f graphviz/docker-compose.yml  up -d && docker stop $(docker ps -a -q)

  "graphviz-publish":
    machine: true
    steps:
      - run:
          name: Publishing graphviz image
          command:
               - docker tag graphviz_jupyter $DOCKER_HUB_USER_ID/graphviz-jupyter:0.0.1
               - docker tag graphviz_jupyter $DOCKER_HUB_USER_ID/graphviz-jupyter:latest
               - docker push $DOCKER_HUB_USER_ID/graphviz-jupyter:0.0.1
               - docker push $DOCKER_HUB_USER_ID/graphviz-jupyter:latest

workflows:
  version: 2
  build:
    jobs:
      - "machine-learning"
      - "machine-learning-publish":
            requires:
              - "machine-learning"
      - "latex"
      - "latex-publish":
            requires:
              - "latex"
      - "graphviz"
      - "graphviz-publish":
            requires:
              - "graphviz"
