version: 2.0

machine:
  services:
    - docker

dependencies:
    override:
       - sudo pip install --upgrade pip
       - sudo pip install docker-compose

jobs:

  machine-learning:
    working_directory: ~/tmp
    environment:
       version: 1.2.0
    machine: true
    steps:
      - checkout
      - run:
          name: Building machine learning image
          command:
             echo $PWD &&
             ls -aslh $PWD &&
             docker-compose -f machine_learning/docker-compose.yml up -d &&
             docker stop $(docker ps -a -q) &&
             docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD &&
             docker tag machinelearning_jupyter $DOCKER_HUB_USER_ID/machine-learning-jupyter:${version} &&
             docker tag machinelearning_jupyter $DOCKER_HUB_USER_ID/machine-learning-jupyter:latest &&
             docker push $DOCKER_HUB_USER_ID/machine-learning-jupyter:${version} &&
             docker push $DOCKER_HUB_USER_ID/machine-learning-jupyter:latest


  latex:
    working_directory: ~/tmp
    environment:
       version: 1.0.0
    machine: true
    steps:
      - checkout
      - run:
          name: Building latex image
          command:
             echo $PWD &&
             ls -aslh $PWD &&
             docker-compose -f latex/docker-compose.yml  up -d &&
             docker stop $(docker ps -a -q) &&
             docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD &&
             docker tag latex_jupyter $DOCKER_HUB_USER_ID/latex-jupyter:${version} &&
             docker tag latex_jupyter $DOCKER_HUB_USER_ID/latex-jupyter:latest &&
             docker push $DOCKER_HUB_USER_ID/latex-jupyter:${version} &&
             docker push $DOCKER_HUB_USER_ID/latex-jupyter:latest

  graphviz:
    working_directory: ~/tmp
    environment:
       version: 1.0.0
    machine: true
    steps:
      - checkout
      - run:
          name: Building graphviz image
          command:
             echo $PWD &&
             ls -aslh $PWD &&
             docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD &&
             docker-compose -f graphviz/docker-compose.yml  up -d &&
             docker stop $(docker ps -a -q) &&
             docker tag graphviz_jupyter $DOCKER_HUB_USER_ID/graphviz-jupyter:${version} &&
             docker tag graphviz_jupyter $DOCKER_HUB_USER_ID/graphviz-jupyter:latest &&
             docker push $DOCKER_HUB_USER_ID/graphviz-jupyter:${version} &&
             docker push $DOCKER_HUB_USER_ID/graphviz-jupyter:latest

  finance:
    working_directory: ~/tmp
    environment:
       version: 1.0.0
    machine: true
    steps:
      - checkout
      - run:
          name: Building finance image
          command:
             echo $PWD &&
             ls -aslh $PWD &&
             docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD &&
             docker-compose -f finance/docker-compose.yml  up -d &&
             docker stop $(docker ps -a -q) &&
             docker tag finance_jupyter $DOCKER_HUB_USER_ID/finance-jupyter:${version} &&
             docker tag finance_jupyter $DOCKER_HUB_USER_ID/finance-jupyter:latest &&
             docker push $DOCKER_HUB_USER_ID/finance-jupyter:${version} &&
             docker push $DOCKER_HUB_USER_ID/finance-jupyter:latest

  ibm-watson-nlp:
    working_directory: ~/tmp
    environment:
       version: 1.0.0
    machine: true
    steps:
      - checkout
      - run:
          name: Building ibm-watson-nlp image
          command:
             echo $PWD &&
             ls -aslh $PWD &&
             docker login --help &&
             docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD &&
             docker-compose -f ibm-watson-nlp/docker-compose.yml  up -d &&
             docker stop $(docker ps -a -q) &&
             docker tag ibmwatsonnlp_jupyter $DOCKER_HUB_USER_ID/ibm-watson-nlp-jupyter:${version} &&
             docker tag ibmwatsonnlp_jupyter $DOCKER_HUB_USER_ID/ibm-watson-nlp-jupyter:latest &&
             docker push $DOCKER_HUB_USER_ID/ibm-watson-nlp-jupyter:${version} &&
             docker push $DOCKER_HUB_USER_ID/ibm-watson-nlp-jupyter:latest

workflows:
  version: 2
  build:
    jobs:
      - machine-learning
      - latex
      - graphviz
      - finance
      - ibm-watson-nlp
